[[pages]]
path = "pages/Homepage.py"
name = "Homepage"
icon = "ğŸ "

[[pages]]
name = "User Actions"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "pages/My_Recipes.py"
name = "My Recipes"
icon = "ğŸ‘¨â€ğŸ³"

[[pages]]
path = "pages/Create_Recipes.py"
name = "Create Recipes"
icon = "ğŸ³"

[[pages]]
path = "pages/Search_Recipes.py"
name = "Search Recipes"
icon = "ğŸ½ï¸"

[[pages]]
name = "Options"
icon = "â“"
is_section = true

[[pages]]
path = "pages/Settings.py"
name = "Settings"
icon = "âš™ï¸"

[[pages]]
path = "pages/Logout.py"
name = "Logout"
icon = "â†ª"